### ISSUE TITLE
Wrong version shown in latest release

### ISSUE THREAD

**Issue by suschizu** [choll/packetpeeper#1] opened 2019-12-16 18:05 UTC
Hello!
I've just downloaded the latest release of packetpeeper (should be 2019-11-21) - but the app still contains version 2019-11-11.
![image](https://user-images.githubusercontent.com/16004333/70930982-baa63900-2036-11ea-96b4-425f01727617.png)

**Comment by choll** [comment] 2019-12-17 12:45
Hi,

Thanks for reporting this, looks like the plist isn't being automatically updated. I've manually updated the plist and created a new release if you want to try it:

https://github.com/choll/packetpeeper/releases/tag/2019-12-17

I will look into why the build didn't automatically update the plist.

Thanks
Chris

**Comment by suschizu** [comment] 2019-12-17 13:45
i can confirm this is fixed in the re-release. thanks!

**Comment by choll** [comment] 2019-12-20 21:49
Seems like the root cause is Azure Pipelines not allowing files to be modified during a build, closing the ticket.

**Closed as completed by choll** 2019-12-20 21:49 UTC
Labels: bug
